name: reviews_slider
description: Animated widget with changing smile to collect user review score.
author: Kherel Kechil <kherel@gmail.com>
homepage: https://github.com/kherel/reviews_slider

version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
